[package]
name = "proof-of-stake"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
anyhow = "1.0"
chrono = "0.4"
ed25519-dalek={version="2.1", features=["rand_core"]}
sha2 = "0.10"
